services:
  web:
    image: maithuc2003/go-book-api:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=thuc123
      - MYSQL_DATABASE=tbl_test_golang
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql #This helps persist the database data even if the container is stopped or removed
volumes:
  db:

# TỰ động merge chỉ cần github bấm merge thì bên docker hub tự login ,tự push 
# Vì trong trường hợp như 1000 dev thì không phải tự động bằng tay được