version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: dockerfile
    # image: maithuc2003/go-book-api:latest
    depends_on:
      - db
    ports:
      - "${PORT}:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./db:/var/lib/mysql

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
